<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{link}">This</a> is link for reset your password. If you did not request it ignore this letter.' => '<a href="{link}">Эта</a> ссылка для сброса пароля. Если вы не хотите этого, просто проигнорируйте данное сообщение.',
    'Add social service' => 'Добавить соц. сеть',
    'AuthClient class name' => '',
    'AuthClient parameters' => '',
    'BEM modifier' => '',
    'Back' => 'Назад',
    'Biz Rule' => '',
    'Change Password' => 'Изменить пароль',
    'Check your email for further instructions.' => 'Проверьте ваш e-mail для дальнейших инструкций.',
    'Children' => 'Дочерние элементы',
    'Confirm Password' => 'Подтверждение пароля',
    'Create' => 'Создать',
    'Create Permission' => 'Создать разрешение',
    'Create Role' => 'Создать роль',
    'Created at' => 'Создано',
    'Delete' => 'Удалить',
    'Delete selected' => 'Удалить выделенные',
    'Delete social service' => 'Удалить соц. сеть',
    'Description' => 'Описание',
    'E-Mail' => '',
    'Edit' => 'Изменить',
    'Hello' => 'Здравствуйте',
    'Invalid login or password' => 'Неправильный логин или пароль',
    'Item <strong>{value}</strong> is not assigned:' => '',
    'Login' => 'Войти',
    'Login to site' => 'Авторизация',
    'Login using social network' => 'Войти через соц. сеть',
    'Logout' => '@@Выйти@@',
    'Manage Social' => 'Управление соц. сетями',
    'Name' => 'Название',
    'New Password' => 'Новый пароль',
    'Old Name' => 'Старое название',
    'Old Password' => 'Старый пароль',
    'Old Password not valid' => 'Не правильный старый пароль',
    'Password' => 'Пароль',
    'Permissions' => 'Разрешения',
    'Phone' => 'Телефон',
    'Please fill recommended profile fields.' => '',
    'Please fill required profile fields.' => '',
    'Profile update' => 'Изменение профиля',
    'Rbac' => '',
    'Record has been saved' => '',
    'Register' => 'Зарегистрироваться',
    'Register using social network' => 'Зарегистрироваться через соц. сеть',
    'Registration' => 'Регистрация',
    'Remember me' => 'Запомнить меня',
    'Request to reset password' => 'Запрос на сброс пароля',
    'Reset Password' => 'Сбросить пароль',
    'Reset password' => 'Сбросить пароль',
    'Roles' => 'Роли',
    'Save' => 'Сохранить',
    'Save & Go back' => 'Сохранить и вернуться',
    'Save & Go next' => 'Сохранить и новый',
    'Service has been deleted' => 'Сервис был удален',
    'Service has not been deleted' => '',
    'Social service' => '',
    'Social service attributes' => '',
    'This email address has already been taken' => '',
    'This username has already been taken' => '',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Updated at' => 'Обновлено',
    'User ID' => '',
    'User ID in social service' => '',
    'User attribute' => '',
    'Username' => 'Логин',
    'You need to confirm your email address' => '',
    'Your password has been changed' => 'Ваш пароль был изменен',
    'Your profile sucessfully updated.' => '',
];
